# Generated by Django 3.2.23 on 2024-02-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0005_auto_20240216_1545'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Achievment',
            new_name='Achievement',
        ),
        migrations.RenameModel(
            old_name='AchievmentCat',
            new_name='AchievementCat',
        ),
        migrations.RenameField(
            model_name='achievementcat',
            old_name='achievment',
            new_name='achievement',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='achievments',
        ),
        migrations.AddField(
            model_name='cat',
            name='achievements',
            field=models.ManyToManyField(through='cats.AchievementCat', to='cats.Achievement'),
        ),
    ]
